logFilters:
  - code: YN0002 # https://yarnpkg.com/advanced/error-codes#yn0002---missing_peer_dependency
    level: discard
  - code: YN0060 # https://yarnpkg.com/advanced/error-codes#yn0060---incompatible_peer_dependency
    level: discard

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.1.1.cjs
